// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const resetDB = `-- name: ResetDB :exec
TRUNCATE TABLE users, feeds, feed_follows CASCADE
`

func (q *Queries) ResetDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDB)
	return err
}
